### ISSUE TITLE
Ruuning the package

### ISSUE THREAD

**Issue by Qazi-Murad** [amanmdesai/lhereader#1]
Hi again. Thank you so much for your quick response. I followed your instructions, and successfully covert the LHE file. Now I want to analyze the root file. I have 4 b quarks in the final state, among which 2 b's coming from diquarks. I am looking to identify these 2 b's originating from the primary vertex. Any advice?

**Comment by amanmdesai** [comment]
Hi @Qazi-Murad.

I am assuming you are analysing the LHE files generated from MadGraph.
If you are considering a truth based analysis - you could use the PID variable (particle pdg code) to access the b-quark, being sure to select the b-quark in the final state using the "Status" variable.

**Comment by Qazi-Murad** [comment]
Yes, you are right. I generated this LHE file from MadGraph. Let me try. Thanks
